//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProc.SMSSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ynssxsoft.com", ConfigurationName="SMSSvc.ISMSService")]
    public interface ISMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ynssxsoft.com/ISMSService/SendMessage", ReplyAction="http://www.ynssxsoft.com/ISMSService/SendMessageResponse")]
        TalentGo.SMSSvc.SendMessageResult SendMessage(string[] ToList, string Message, TalentGo.SMSSvc.SendMessageOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ynssxsoft.com/ISMSService/SendMessage", ReplyAction="http://www.ynssxsoft.com/ISMSService/SendMessageResponse")]
        System.Threading.Tasks.Task<TalentGo.SMSSvc.SendMessageResult> SendMessageAsync(string[] ToList, string Message, TalentGo.SMSSvc.SendMessageOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ynssxsoft.com/ISMSService/GetReceivedMessage", ReplyAction="http://www.ynssxsoft.com/ISMSService/GetReceivedMessageResponse")]
        TalentGo.SMSSvc.ReceivedMessage GetReceivedMessage(int SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ynssxsoft.com/ISMSService/GetReceivedMessage", ReplyAction="http://www.ynssxsoft.com/ISMSService/GetReceivedMessageResponse")]
        System.Threading.Tasks.Task<TalentGo.SMSSvc.ReceivedMessage> GetReceivedMessageAsync(int SessionID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSServiceChannel : DataProc.SMSSvc.ISMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceClient : System.ServiceModel.ClientBase<DataProc.SMSSvc.ISMSService>, DataProc.SMSSvc.ISMSService {
        
        public SMSServiceClient() {
        }
        
        public SMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TalentGo.SMSSvc.SendMessageResult SendMessage(string[] ToList, string Message, TalentGo.SMSSvc.SendMessageOption option) {
            return base.Channel.SendMessage(ToList, Message, option);
        }
        
        public System.Threading.Tasks.Task<TalentGo.SMSSvc.SendMessageResult> SendMessageAsync(string[] ToList, string Message, TalentGo.SMSSvc.SendMessageOption option) {
            return base.Channel.SendMessageAsync(ToList, Message, option);
        }
        
        public TalentGo.SMSSvc.ReceivedMessage GetReceivedMessage(int SessionID) {
            return base.Channel.GetReceivedMessage(SessionID);
        }
        
        public System.Threading.Tasks.Task<TalentGo.SMSSvc.ReceivedMessage> GetReceivedMessageAsync(int SessionID) {
            return base.Channel.GetReceivedMessageAsync(SessionID);
        }
    }
}
