//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable

namespace TalentGo.ValidationCodeSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/CommonServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TalentGo.ValidationCodeSvc.SendVerificationCodeOperationResult))]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendVerificationCodeOperationResult", Namespace="http://www.qjyc.cn/ws/2017")]
    [System.SerializableAttribute()]
    public partial class SendVerificationCodeOperationResult : TalentGo.ValidationCodeSvc.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerificationCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerificationCode {
            get {
                return this.VerificationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerificationCodeField, value) != true)) {
                    this.VerificationCodeField = value;
                    this.RaisePropertyChanged("VerificationCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.qjyc.cn/ws/2017", ConfigurationName="ValidationCodeSvc.IVerificationCode")]
    public interface IVerificationCode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qjyc.cn/ws/2017/IVerificationCode/Send", ReplyAction="http://www.qjyc.cn/ws/2017/IVerificationCode/SendResponse")]
        TalentGo.ValidationCodeSvc.SendVerificationCodeOperationResult Send(string Mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qjyc.cn/ws/2017/IVerificationCode/Send", ReplyAction="http://www.qjyc.cn/ws/2017/IVerificationCode/SendResponse")]
        System.Threading.Tasks.Task<TalentGo.ValidationCodeSvc.SendVerificationCodeOperationResult> SendAsync(string Mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qjyc.cn/ws/2017/IVerificationCode/Verify", ReplyAction="http://www.qjyc.cn/ws/2017/IVerificationCode/VerifyResponse")]
        bool Verify(string Mobile, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qjyc.cn/ws/2017/IVerificationCode/Verify", ReplyAction="http://www.qjyc.cn/ws/2017/IVerificationCode/VerifyResponse")]
        System.Threading.Tasks.Task<bool> VerifyAsync(string Mobile, string Code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVerificationCodeChannel : TalentGo.ValidationCodeSvc.IVerificationCode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerificationCodeClient : System.ServiceModel.ClientBase<TalentGo.ValidationCodeSvc.IVerificationCode>, TalentGo.ValidationCodeSvc.IVerificationCode {
        
        public VerificationCodeClient() {
        }
        
        public VerificationCodeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerificationCodeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificationCodeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificationCodeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TalentGo.ValidationCodeSvc.SendVerificationCodeOperationResult Send(string Mobile) {
            return base.Channel.Send(Mobile);
        }
        
        public System.Threading.Tasks.Task<TalentGo.ValidationCodeSvc.SendVerificationCodeOperationResult> SendAsync(string Mobile) {
            return base.Channel.SendAsync(Mobile);
        }
        
        public bool Verify(string Mobile, string Code) {
            return base.Channel.Verify(Mobile, Code);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyAsync(string Mobile, string Code) {
            return base.Channel.VerifyAsync(Mobile, Code);
        }
    }
}

#pragma warning restore